[SEQUENCE_AND_CELL]
# The input genomic sequence must be long enough (recommended >60bp) for inDelphi parsing.
SAMPLE_GENOMIC_SEQUENCE = GCTATCACCTCCGCCGGGGTCACCCATTATCTGGCGGCCCCCCGGAAAGGGGGGGGGGGGGG

# Shared cell line for prediction. Strictly limited to intersection: ['mESC', 'HEK293', 'K562']
CELL_LINE = HEK293

[DEEPONE_ENV]
# Path to your Python 3 executable or alias (where tensorflow, keras, viennarna are installed)
PYTHON3_EXEC = /share/home/ibmc/genomictest/lengke/anaconda3/envs/tf2.4.1/bin/python
# Absolute path to the locally cloned DeepOne repository directory
DEEPONE_DIR = /share/home/ibmc/genomictest/yuanhao2/DeepOne_model/

[INDELPHI_ENV]
# Path to your Python 2.7 executable or alias (where inDelphi dependencies are installed)
PYTHON2_EXEC = /share/home/ibmc/genomictest/lengke/anaconda3/envs/py27/bin/python
# Absolute path to the locally cloned inDelphi repository directory
INDELPHI_DIR = /share/home/ibmc/genomictest/yuanhao2/indelphi/inDelphi-model-master
